spring.application.name=backend
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://bhardwajvivek226_db_user:Vi060507@portfolio.cc1zppi.mongodb.net/expense_tracker?appName=Portfolio}
spring.data.mongodb.database=${MONGODB_DATABASE:expense_tracker}
jwt.secret=${JWT_SECRET:94a08da1fecbb6e8b46990538c7b50b294a08da1fecbb6e8b46990538c7b50b2}
jwt.expiration=${JWT_EXPIRATION:86400000}
server.port=${PORT:8080}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173,http://localhost:5174,http://localhost:3000,https://expence-track-nu.vercel.app,https://expence-track-3azsce5o2-itachi-01-cybers-projects.vercel.app}
app.seed.enabled=${SEED_DEMO_DATA:false}

# Resend Configuration
resend.api.key=re_EaRrfkHf_5kT5Py3Rs3tm2NPvPvbEXz95
resend.from.email=onboarding@resend.dev
